export const TECHNOLOGIES = {
  frontend: [
    {
      name: "Vite + React",
      hosting: ["Vercel", "Netlify", "GitHub Pages"],
      cost: "Gratis",
      build: "~2 min",
      description: "Rápido, moderno, ideal para MVPs y SPAs",
    },
    {
      name: "Next.js",
      hosting: ["Vercel", "Netlify"],
      cost: "Gratis",
      build: "~3 min",
      description: "Full-stack, SSR, excelente para SEO",
    },
    {
      name: "Astro",
      hosting: ["Vercel", "Netlify", "Cloudflare Pages"],
      cost: "Gratis",
      build: "~1 min",
      description: "Ultra rápido, ideal para contenido estático",
    },
    {
      name: "Vue.js + Vite",
      hosting: ["Vercel", "Netlify"],
      cost: "Gratis",
      build: "~2 min",
      description: "Framework progresivo, fácil de aprender",
    },
  ],
  backend: [
    {
      name: "Node.js + Express",
      hosting: ["Railway", "Render", "Fly.io"],
      cost: "Gratis (con límites)",
      description: "Clásico, flexible, gran ecosistema",
    },
    {
      name: "Next.js API Routes",
      hosting: ["Vercel"],
      cost: "Gratis",
      description: "Backend integrado con frontend",
    },
    {
      name: "Fastify",
      hosting: ["Railway", "Render"],
      cost: "Gratis (con límites)",
      description: "Rápido y eficiente",
    },
    {
      name: "Bun + Hono",
      hosting: ["Fly.io", "Railway"],
      cost: "Gratis (con límites)",
      description: "Súper rápido, moderno",
    },
  ],
  api: [
    {
      name: "REST API",
      hosting: ["Cualquier backend"],
      cost: "Incluido",
      description: "Estándar, simple, universal",
    },
    {
      name: "GraphQL",
      hosting: ["Apollo Server", "Hasura"],
      cost: "Gratis (con límites)",
      description: "Flexible, eficiente en queries",
    },
    {
      name: "tRPC",
      hosting: ["Vercel", "Railway"],
      cost: "Gratis",
      description: "Type-safe, ideal con TypeScript",
    },
  ],
  database: [
    {
      name: "MongoDB Atlas",
      hosting: ["Cloud MongoDB"],
      cost: "Gratis (512MB)",
      storage: "512MB",
      description: "NoSQL, flexible, escalable",
    },
    {
      name: "PostgreSQL",
      hosting: ["Supabase", "Neon", "Railway"],
      cost: "Gratis (con límites)",
      storage: "500MB - 1GB",
      description: "SQL robusto, relacional",
    },
    {
      name: "Supabase",
      hosting: ["Supabase Cloud"],
      cost: "Gratis (500MB)",
      storage: "500MB",
      description: "PostgreSQL + Auth + Storage",
    },
    {
      name: "Firebase Firestore",
      hosting: ["Google Cloud"],
      cost: "Gratis (1GB)",
      storage: "1GB",
      description: "NoSQL en tiempo real",
    },
    {
      name: "PlanetScale",
      hosting: ["PlanetScale Cloud"],
      cost: "Gratis (5GB)",
      storage: "5GB",
      description: "MySQL serverless",
    },
  ],
  realtime: [
    {
      name: "Socket.io",
      hosting: ["Railway", "Render"],
      cost: "Gratis (con backend)",
      description: "WebSockets, bidireccional",
    },
    {
      name: "Pusher",
      hosting: ["Pusher Cloud"],
      cost: "Gratis (100 conexiones)",
      description: "Managed, fácil de usar",
    },
    {
      name: "Supabase Realtime",
      hosting: ["Supabase"],
      cost: "Incluido",
      description: "Integrado con Supabase",
    },
    {
      name: "Firebase Realtime DB",
      hosting: ["Google Cloud"],
      cost: "Gratis (1GB)",
      description: "Sincronización en tiempo real",
    },
  ],
  storage: [
    {
      name: "Cloudinary",
      hosting: ["Cloudinary Cloud"],
      cost: "Gratis (25 créditos/mes)",
      description: "Imágenes y videos optimizados",
    },
    {
      name: "Supabase Storage",
      hosting: ["Supabase"],
      cost: "Gratis (1GB)",
      description: "Almacenamiento de archivos",
    },
    {
      name: "AWS S3",
      hosting: ["Amazon Web Services"],
      cost: "Gratis (5GB/año)",
      description: "Escalable, robusto",
    },
    {
      name: "Uploadthing",
      hosting: ["Uploadthing Cloud"],
      cost: "Gratis (2GB)",
      description: "Simple, para Next.js",
    },
  ],
  auth: [
    {
      name: "NextAuth.js",
      hosting: ["Vercel"],
      cost: "Gratis",
      description: "Auth completo para Next.js",
    },
    {
      name: "Clerk",
      hosting: ["Clerk Cloud"],
      cost: "Gratis (10k usuarios)",
      description: "UI completa, fácil integración",
    },
    {
      name: "Supabase Auth",
      hosting: ["Supabase"],
      cost: "Incluido",
      description: "Auth integrado con Supabase",
    },
    {
      name: "Firebase Auth",
      hosting: ["Google Cloud"],
      cost: "Gratis (ilimitado)",
      description: "Múltiples proveedores",
    },
    {
      name: "Auth0",
      hosting: ["Auth0 Cloud"],
      cost: "Gratis (7k usuarios)",
      description: "Enterprise-grade",
    },
  ],
};

export const PREDEFINED_STACKS = [
  {
    id: "landing",
    name: "Landing Page",
    description: "Sitio informativo rápido y optimizado para SEO",
    icon: "📄",
    stack: {
      frontend: {
        enabled: true,
        technology: "Astro",
        hosting: ["Vercel"],
        cost: "Gratis",
        notes: "Perfecto para contenido estático",
      },
      backend: { enabled: false },
      api: { enabled: false },
      database: { enabled: false },
      realtime: { enabled: false },
      storage: {
        enabled: true,
        technology: "Cloudinary",
        hosting: ["Cloudinary Cloud"],
        cost: "Gratis",
        notes: "Para imágenes optimizadas",
      },
      auth: { enabled: false },
    },
  },
  {
    id: "fullstack",
    name: "Full-Stack App",
    description: "Aplicación completa con auth y base de datos",
    icon: "🚀",
    stack: {
      frontend: {
        enabled: true,
        technology: "Next.js",
        hosting: ["Vercel"],
        cost: "Gratis",
      },
      backend: {
        enabled: true,
        technology: "Next.js API Routes",
        hosting: ["Vercel"],
        cost: "Gratis",
      },
      api: {
        enabled: true,
        technology: "REST API",
        hosting: ["Vercel"],
        cost: "Incluido",
      },
      database: {
        enabled: true,
        technology: "MongoDB Atlas",
        hosting: ["Cloud MongoDB"],
        cost: "Gratis (512MB)",
        storage: "512MB",
      },
      realtime: { enabled: false },
      storage: {
        enabled: true,
        technology: "Uploadthing",
        hosting: ["Uploadthing Cloud"],
        cost: "Gratis (2GB)",
      },
      auth: {
        enabled: true,
        technology: "NextAuth.js",
        hosting: ["Vercel"],
        cost: "Gratis",
      },
    },
  },
  {
    id: "realtime",
    name: "Real-Time App",
    description: "Chat, colaboración, o dashboard en tiempo real",
    icon: "⚡",
    stack: {
      frontend: {
        enabled: true,
        technology: "Vite + React",
        hosting: ["Vercel"],
        cost: "Gratis",
      },
      backend: {
        enabled: true,
        technology: "Node.js + Express",
        hosting: ["Railway"],
        cost: "Gratis (con límites)",
      },
      api: {
        enabled: true,
        technology: "REST API",
        hosting: ["Railway"],
        cost: "Incluido",
      },
      database: {
        enabled: true,
        technology: "Supabase",
        hosting: ["Supabase Cloud"],
        cost: "Gratis (500MB)",
        storage: "500MB",
      },
      realtime: {
        enabled: true,
        technology: "Socket.io",
        hosting: ["Railway"],
        cost: "Gratis (con backend)",
      },
      storage: {
        enabled: true,
        technology: "Supabase Storage",
        hosting: ["Supabase"],
        cost: "Gratis (1GB)",
      },
      auth: {
        enabled: true,
        technology: "Supabase Auth",
        hosting: ["Supabase"],
        cost: "Incluido",
      },
    },
  },
  {
    id: "ecommerce",
    name: "E-Commerce",
    description: "Tienda online completa con pagos",
    icon: "🛒",
    stack: {
      frontend: {
        enabled: true,
        technology: "Next.js",
        hosting: ["Vercel"],
        cost: "Gratis",
      },
      backend: {
        enabled: true,
        technology: "Next.js API Routes",
        hosting: ["Vercel"],
        cost: "Gratis",
      },
      api: {
        enabled: true,
        technology: "REST API",
        hosting: ["Vercel"],
        cost: "Incluido",
      },
      database: {
        enabled: true,
        technology: "PostgreSQL",
        hosting: ["Supabase"],
        cost: "Gratis (500MB)",
        storage: "500MB",
      },
      realtime: { enabled: false },
      storage: {
        enabled: true,
        technology: "Cloudinary",
        hosting: ["Cloudinary Cloud"],
        cost: "Gratis (25 créditos/mes)",
      },
      auth: {
        enabled: true,
        technology: "Clerk",
        hosting: ["Clerk Cloud"],
        cost: "Gratis (10k usuarios)",
      },
    },
  },
  {
    id: "pwa",
    name: "Progressive Web App",
    description: "App móvil con capacidades offline",
    icon: "📱",
    stack: {
      frontend: {
        enabled: true,
        technology: "Next.js",
        hosting: ["Vercel"],
        cost: "Gratis",
        notes: "Con PWA plugin",
      },
      backend: {
        enabled: true,
        technology: "Next.js API Routes",
        hosting: ["Vercel"],
        cost: "Gratis",
      },
      api: {
        enabled: true,
        technology: "REST API",
        hosting: ["Vercel"],
        cost: "Incluido",
      },
      database: {
        enabled: true,
        technology: "Firebase Firestore",
        hosting: ["Google Cloud"],
        cost: "Gratis (1GB)",
        storage: "1GB",
      },
      realtime: {
        enabled: true,
        technology: "Firebase Realtime DB",
        hosting: ["Google Cloud"],
        cost: "Gratis (1GB)",
      },
      storage: {
        enabled: true,
        technology: "Firebase Storage",
        hosting: ["Google Cloud"],
        cost: "Gratis (5GB)",
      },
      auth: {
        enabled: true,
        technology: "Firebase Auth",
        hosting: ["Google Cloud"],
        cost: "Gratis (ilimitado)",
      },
    },
  },
];
